# Generated by Django 5.2.7 on 2025-10-30 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='ชื่อลูกค้า')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('preparing', 'กำลังเตรียม'), ('ready', 'พร้อมเสิร์ฟ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดรวม')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สั่ง')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
            ],
            options={
                'verbose_name': 'ออเดอร์',
                'verbose_name_plural': 'ออเดอร์',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='หมายเลขโต๊ะ')),
                ('capacity', models.IntegerField(verbose_name='จำนวนที่นั่ง')),
                ('status', models.CharField(choices=[('available', 'ว่าง'), ('occupied', 'มีคนนั่ง'), ('reserved', 'จอง')], default='available', max_length=20, verbose_name='สถานะ')),
            ],
            options={
                'verbose_name': 'โต๊ะ',
                'verbose_name_plural': 'โต๊ะ',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อเมนู')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='รูปภาพ')),
                ('is_available', models.BooleanField(default=True, verbose_name='พร้อมจำหน่าย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'เมนูอาหาร',
                'verbose_name_plural': 'เมนูอาหาร',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวน')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคารวม')),
                ('special_instructions', models.TextField(blank=True, verbose_name='คำขอพิเศษ')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menuitem', verbose_name='เมนู')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='ออเดอร์')),
            ],
            options={
                'verbose_name': 'รายการสั่ง',
                'verbose_name_plural': 'รายการสั่ง',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.table', verbose_name='โต๊ะ'),
        ),
    ]
